# Generated by Django 4.0.4 on 2022-05-31 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Actor', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('foto_Actor', models.ImageField(blank=True, upload_to='')),
                ('anio_nacimiento', models.DateField()),
                ('resumen_Bibliografico', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_Admin', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Director', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('foto_Director', models.ImageField(blank=True, upload_to='')),
                ('anio_nacimiento', models.DateField()),
                ('resumen_Bibliografico', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=30)),
                ('resumen', models.CharField(max_length=350)),
                ('anio_de_Lanzamiento', models.DateField()),
                ('puntaje', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('actores', models.ManyToManyField(to='Cartelera.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Cartelera.director')),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
                ('puntaje', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resenia', models.CharField(max_length=400)),
                ('nombre_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartelera.pelicula')),
            ],
        ),
    ]
