# Generated by Django 4.0.4 on 2022-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0002_critica_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='image/Pelis'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='critica',
            name='validacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='bio',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(related_name='peliculas', to='Cartelera.actor'),
        ),
    ]
