# Generated by Django 4.0.4 on 2022-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0003_pelicula_foto_alter_actor_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actores'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
