# Generated by Django 4.0.4 on 2022-06-27 07:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0004_alter_actor_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartelera.pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='image/Pelis/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='puntaje',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
